site_name: m2dtools
site_url: https://zyumse.github.io/m2dtools/

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers: 
        python:
          options:
            docstring_style: numpy

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Functions:
      - Lammps: references/lmp.md
      - Basic:
        - Structure: references/basic/structure.md
        - Dynamics: references/basic/dynamics.md
        - Basic: references/basic/basic.md
      # - cg: references/cg.md
      # - network: reference/network.md
      - Other: references/other.md

